engines:
    eslint:
        enabled: true
        checks:
            # Can extends native objects
            no-extend-native:
                enabled: false
    fixme:
        enabled: true

ratings:
    paths:
        - "**.js"

exclude_paths:
    - "**.min.js"
    - spec/**/*
